spring:
  redis:
    delay:
      host: 192.168.1.221
      port: 16379
      database: 1
  application:
    name: dp
server:
  port: 8081
logging:
  level:
    root: info
    io.github.booksongs: debug

